DROP TABLE IF EXISTS kiwi;
CREATE TABLE kiwi ("id" serial not null primary key, "kiwiWord" varchar(255), "expression" varchar(255));
INSERT INTO kiwi VALUES(1,'cuzzy','cousin');
INSERT INTO kiwi VALUES(2,'choice','a good pick');
INSERT INTO kiwi VALUES(3,'chocolate fish','chocolate covered pink marshmallow');
INSERT INTO kiwi VALUES(4,'crook','feeling sick');
INSERT INTO kiwi VALUES(5,'chook','chicken');
INSERT INTO kiwi VALUES(6,'togs','bathing suit');
INSERT INTO kiwi VALUES(7,'tea','dinner');
INSERT INTO kiwi VALUES(8,'Maccas','McDonalds');
INSERT INTO kiwi VALUES(9,'sparky','electrician');
INSERT INTO kiwi VALUES(10,'tomato sauce','ketchup');
INSERT INTO kiwi VALUES(11,'rubber','eraser(not a condom)');
INSERT INTO kiwi VALUES(12,'smoko','tea break');
INSERT INTO kiwi VALUES(13,'bogan','unsophisticated person');
INSERT INTO kiwi VALUES(14,'prawns','big shrimp');
INSERT INTO kiwi VALUES(15,'hangi','a traditional Maori meal  and veggies');
INSERT INTO kiwi VALUES(16,'dunny','toilet');
INSERT INTO kiwi VALUES(17,'sunnies','sunglasses');
INSERT INTO kiwi VALUES(18,'caridgan','cardy');
INSERT INTO kiwi VALUES(19,'jandals','flip flops');
INSERT INTO kiwi VALUES(20,'gummies','rubber boots');
INSERT INTO kiwi VALUES(21,'benny','welfare');
