#!/usr/bin/env node
var knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: __dirname + '/dev.sqlite3'
  },
  useNullAsDefault: true
})

var cmd = process.argv[2]
var note = process.argv[3]
var updateId = process.argv[4]


switch (cmd) {

  case 'list':
  getAll()
  .then(listTodos)
  .catch(logError)
  .finally(closeDB)
  break

  case 'search':
  search(note)
  .then(listTodos)
  .catch(logError)
  .finally(closeDB)
  break

  case 'wordMatch':
  wordMatch()
  .then(listTodos)
  .catch(logError)
  .finally(closeDB)
  break


  default:
  console.log('no matched cases')
  closeDB()
  break
}



function listTodos (kiwiWords) {
  kiwiWords.forEach(function (word) { console.log(word.id, word.kiwiWord, word.expression)
})
}
//-----select by ID -----
function wordMatch(){
  var randomNumber = Math.floor((Math.random() * 21) + 1)
  return knex.raw('SELECT id,kiwiWord,expression FROM "kiwi" WHERE id=' + randomNumber + ';')
}

function logError (err) {
  console.log('Dang, we exploded like a bomb: ', err)
}
function getAll () {
  return knex.raw('select * from "kiwi"')
}

function search(task){
  return knex.raw('select * from "todos" WHERE task LIKE "%' + task + '%"')
}

function closeDB () {
  knex.destroy()
}
